### ISSUE TITLE
dubbo引入docker,dubbo后台的服务列表不会实时更新

### ISSUE THREAD

**Issue by zilanghuo** [dubbo/dubbo-samples#11]
打扰下，请教下个问题：dodocker的启动命令：-e DUBBO_IP_TO_REGISTRY=172.17.35.10 -e DUBBO_PORT_TO_REGISTRY=19094
出现了多个同样的信息，这个什么原因造成的？
![tim 20180712164110](https://user-images.githubusercontent.com/15532623/42622288-a14ada86-85f2-11e8-8b3f-a1c78cc26959.jpg)

**Comment by ningyu1** [comment]
@zilanghuo 同一台宿主机docker run多个容器都是同一个registry ip和端口的话是会有这个问题， 同一个provider的服务最好去不同的宿主机上run容器。

**Comment by zilanghuo** [comment]
@ningyu1 我这边是docker 一个项目而已。就是docker ps 其实就一个容器，我测试的时候，是docker run 一个服务，然后再docker rm 这个容器。。就是不会实时的更新服务列表。正常的话，应该就只有一个服务列表而已，因为我就启动一个容器

**Comment by ningyu1** [comment]
@zilanghuo 那你应该在问题描述中说明一下，是dubbo admin中数据展示以及更新问题，如果确定是admin的问题 建议你去ops项目下提一个issue

**Comment by zilanghuo** [comment]
@ningyu1 嗯，谢谢
