### ISSUE TITLE
生产者需要添加@HystrixCommand吗？

### ISSUE THREAD

**Issue by renrg** [dubbo/dubbo-samples#18]
@HystrixCommand(commandProperties = {
            @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "10"),
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "2000") })
	@Override
	public String sayHello(String name) {}

**Comment by diecui1202** [comment]
@hengyunabc

**Comment by hengyunabc** [comment]
@renrg 提供可重现的demo ，另外这个配置和是否生产环境没有关系。“不能提供服务”也需要详细说明。
